package my.weatherApp;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.NativeButton;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.NativeSelect;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.Grid;


/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Weather extends FormLayout {
    protected GridLayout gridLayout;
    protected Label headerLabel;
    protected Panel weatherBoard;
    protected Label weatherHeader;
    protected NativeSelect<String> cityName;
    protected Label todayWeather;
    protected Label tomorrowWeather;
    protected NativeButton updateWeather;
    protected Panel currencyBoard;
    protected Label currencyHeader;
    protected Grid<my.weatherApp.model.CurrencyRate> currencyTable;
    protected NativeButton updateCurrency;
    protected Panel visitBoard;
    protected Label visitHeader;
    protected Label counter;
    protected Label dateInfo;
    protected Label ipInfo;

    public Weather() {
        Design.read(this);
    }

}
